# Generated by Django 4.2.8 on 2023-12-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_clothe_price_alter_clothe_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.clothe', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product.categories_type', verbose_name='Категория'),
        ),
    ]
