# Generated by Django 4.2.8 on 2023-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_type',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
